version: '3.8'
services:
  xlib_db:
    container_name: xlib-postgress
    hostname: xlib_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: xlib_db
    volumes:
      - xlib_postgres:/var/lib/postgresql/data
volumes:
  xlib_postgres:
    driver: local
