version: '3.8'
services:
  xlib_db:
    container_name: xlib-postgress
    hostname: xlib_db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pa$$w0rd1234
      - POSTGRES_USER=admin
      - POSTGRES_DB=xlib_db
    ports:
      - '5432:5432'
    volumes:
      - xlib-db-data:/var/lib/postgresql/data
volumes:
  xlib-db-data:
    driver: local
