version: '3.8'
services:
  xlib_db:
    container_name: xlib-postgress
    hostname: xlib_db
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - xlib-db-data:/var/lib/postgresql/data
volumes:
  xlib-db-data:
    driver: local
