apiVersion: v1
kind: Service
metadata:
  name: postgres-xlib-service
  labels:
    app: postgres-xlib
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres-xlib
